#!/usr/bin/env node
// Generate a comprehensive bundle entry for design-sync.
//
// Why: skateboard-ui's published `.` barrel (dist/index.js) re-exports only a few
// utilities — the real components are exposed solely via package subpath exports
// (`./ui/*`, `./Sidebar`, `./Header`, …). Pointed at the barrel the converter finds
// ZERO components. This emits an entry that re-exports the full component surface so
// every component lands in window.SkateboardUI.* and gets a card.
//
// Canonical set:
//   • ui/*  — the base-ui primitive port (named exports). The first-class primitives.
//   • components/*  — app-level components (default exports → named).
//   • Skips shadcn/ui/*  — legacy duplicates of ui/* (same export names → collisions).
//   • Skips ui/use-*  — hooks, not components.
//
// Name collisions (Sidebar, Sheet) resolve to the app-level component: an explicit
// named re-export shadows an `export *` star export per the ESM spec.
//
// Output: .design-sync/.cache/full-entry.mjs (gitignored; regenerated each build).
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const dsDir = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(dsDir, '..');
const cacheDir = path.join(dsDir, '.cache');
fs.mkdirSync(cacheDir, { recursive: true });

const lines = [
  '// AUTO-GENERATED by .design-sync/gen-entry.mjs — do not edit.',
  '// Comprehensive component surface for window.SkateboardUI.*',
  '',
  '// ── ui/* primitives (base-ui port) ──',
];

// All ui/* component modules, minus hooks.
const uiDir = path.join(root, 'dist', 'ui');
const uiFiles = fs.readdirSync(uiDir)
  .filter((f) => f.endsWith('.js') && !f.startsWith('use-'))
  .sort();
for (const f of uiFiles) lines.push(`export * from '../../dist/ui/${f}';`);

lines.push('', '// ── app-level components (default exports) ──');
// [exported name, dist path] — names taken from the package exports map.
const defaults = [
  ['Header', 'components/layout/Header.js'],
  ['Sidebar', 'components/layout/Sidebar.js'],        // shadows ui/sidebar Sidebar
  ['Layout', 'components/layout/Layout.js'],
  ['TabBar', 'components/layout/TabBar.js'],
  ['LandingView', 'components/views/LandingView.js'],
  ['NotFound', 'components/views/NotFound.js'],
  ['PaymentView', 'components/views/PaymentView.js'],
  ['SettingsView', 'components/views/SettingsView.js'],
  ['SignInView', 'components/views/SignInView.js'],
  ['SignUpView', 'components/views/SignUpView.js'],
  ['SignOutView', 'components/views/SignOutView.js'],
  ['TextView', 'components/views/TextView.js'],
  ['ThemeToggle', 'components/ThemeToggle.js'],
  ['Sheet', 'components/Sheet.js'],                   // shadows ui/sheet Sheet
  ['UpgradeSheet', 'components/UpgradeSheet.js'],
  ['AuthOverlay', 'components/AuthOverlay.js'],
  ['ErrorBoundary', 'components/ErrorBoundary.js'],
  ['ProtectedRoute', 'components/ProtectedRoute.js'],
  ['DynamicIcon', 'components/core/DynamicIcon.js'],
];
for (const [name, p] of defaults) {
  lines.push(`export { default as ${name} } from '../../dist/${p}';`);
}

lines.push('', '// ── named providers ──');
lines.push("export { ThemeProvider } from '../../dist/components/core/ThemeProvider.js';");
lines.push("export { ContextProvider } from '../../dist/components/core/Context.js';");

const out = lines.join('\n') + '\n';
const outPath = path.join(cacheDir, 'full-entry.mjs');
fs.writeFileSync(outPath, out);
console.error(`[gen-entry] wrote ${path.relative(root, outPath)} (${uiFiles.length} ui modules + ${defaults.length} app components)`);
